// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrum9MAWXK8mVB3eLY_D4MbU16Zu2GC1o',
    appId: '1:349699138687:web:694fe434542e966c0bcb4a',
    messagingSenderId: '349699138687',
    projectId: 'chatapplication-dc4f3',
    authDomain: 'chatapplication-dc4f3.firebaseapp.com',
    storageBucket: 'chatapplication-dc4f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWviqhbdGgZYRvJbPhvRzZ1jSRZxchWDA',
    appId: '1:349699138687:android:05f60fd62bd81b780bcb4a',
    messagingSenderId: '349699138687',
    projectId: 'chatapplication-dc4f3',
    storageBucket: 'chatapplication-dc4f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb0TIz_WfJnuPYxUopNOyUTUx3SuaLCzY',
    appId: '1:349699138687:ios:2b14dcefb25531f80bcb4a',
    messagingSenderId: '349699138687',
    projectId: 'chatapplication-dc4f3',
    storageBucket: 'chatapplication-dc4f3.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrum9MAWXK8mVB3eLY_D4MbU16Zu2GC1o',
    appId: '1:349699138687:web:0533eef65c041e150bcb4a',
    messagingSenderId: '349699138687',
    projectId: 'chatapplication-dc4f3',
    authDomain: 'chatapplication-dc4f3.firebaseapp.com',
    storageBucket: 'chatapplication-dc4f3.firebasestorage.app',
  );
}
